os:
  - linux
  - osx
dist: xenial
osx_image: xcode10.1
language: node_js
  - 10
cache:
  - apt: true
  - yarn: true
  - directories:
      - node_modules
      - $HOME/.electron
addons:
  apt:
    packages: zip
  homebrew:
    packages: zip
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn add --dev node@8.15.0; fi
install:
  - yarn
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn build-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn build-darwin; fi
after_success: if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash pack.sh; fi
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "./build/packed/*.{zip,dmg}"
  file_glob: true
  skip_cleanup: true
  on:
    branch: master
    tags: true
    all_branches: true
