os:
  - linux
  - osx
dist: xenial
osx_image: xcode10.1
language: node_js
  - 10
cache:
  - apt: true
  - directories:
      - node_modules
      - $HOME/.electron
addons:
  apt:
    packages: zip
  homebrew:
    packages: zip
before_install:
  - npm install -g yarn --cache-min 999999999
install:
  - yarn add --dev node@8.15.0
  - yarn
script:
  - yarn dist
