cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

install:
  - ps: Install-Product node 10
  - yarn
  - node --version
build_script:
  - yarn dist
